# Welcome to Jekyll!
#

# Site settings
title: Download.NUS
description: |
  A student-run mirror  
  in the heart of Singapore  
  maintained by [NUS Hackers](http://nushackers.org)
owner: NUS Hackers # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: mirror@nushackers.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://download.nus.edu.sg" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/nushackers
  github: https://github.com/nushackers
  facebook-official: https://facebook.com/nushackers
  google-plus-square: https://plus.google.com/116062151863023912691
  email: mailto:mirror@nushackers.org
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
