/**
 * `InternalLdapError` error.
 *
 * InternalLdapError wraps errors generated by ldapjs.  By wrapping these
 * objects, error messages can be formatted in a manner that aids in debugging
 * LDAP issues.
 *
 * @api public
 */

function InternalLdapError(message, err) {
    Error.call(this);
    Error.captureStackTrace(this, arguments.callee);
    this.name = 'InternalLdapError';
    this.message = message;
    this.openidError = err;
};

/**
 * Inherit from `Error`.
 */
InternalLdapError.prototype.__proto__ = Error.prototype;

/**
 * Returns a string representing the error.
 *
 * @return {String}
 * @api public
 */
InternalLdapError.prototype.toString = function() {
    var m = this.message;
    return m;
}


/**
 * Expose `InternalOpenIDError`.
 */
module.exports = InternalLdapError;
